import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Privacy Policy — Zitto',
};

/*
 * PLACEHOLDER CONTENT — see the note in ../terms/page.tsx.
 * Renders from the `cms_pages` row with slug `privacy` in the shipped product.
 */

const SECTIONS = [
  {
    heading: 'What we collect',
    body: [
      'Account details you give us: an email address or mobile number, a display name, and your language preference.',
      'Play data generated by using Zitto: rounds you took part in, coin movements, missions, and tournament results.',
      'Technical data needed to keep the account secure: IP address, device type, and approximate location derived from the IP — used to show you your own active sessions and to spot account takeovers.',
    ],
  },
  {
    heading: 'What we do not collect',
    body: [
      'No payment details. Zitto has no real-money features enabled, so there is nothing to charge and no card to store.',
      'No contact list, no photos, no precise GPS location.',
    ],
  },
  {
    heading: 'How we use it',
    body: [
      'To run your account and show your own history back to you.',
      'To keep the game fair — spotting duplicate accounts, collusion in tournaments, and automated play.',
      'To send the notifications you have switched on. You can turn any of them off in Settings.',
    ],
  },
  {
    heading: 'Analytics about you, shown to you',
    body: [
      'Your analytics screen is computed from your own rounds. It is not shared with other players, and your profile can be hidden from public leaderboards.',
    ],
  },
  {
    heading: 'Who else sees it',
    body: [
      'Our staff, only where they need to — support agents see tickets, admins see account status. Every administrative action that touches an account is written to an audit log with a reason attached.',
      'Service providers who host the application and deliver one-time codes by email or SMS. They process the data on our instructions and nothing more.',
      'We do not sell personal data.',
    ],
  },
  {
    heading: 'How long we keep it',
    body: [
      'Account and play data stays while your account is open. If you delete your account we remove personal details, but round records and ledger entries are kept in a de-identified form because they are part of an immutable, auditable history.',
    ],
  },
  {
    heading: 'Your controls',
    body: [
      'Export your data or request deletion from Settings.',
      'Review and revoke active sessions from Security settings.',
      'Exclude yourself from the platform from the Responsible Gaming page.',
    ],
  },
];

export default function PrivacyPage() {
  return (
    <>
      <h1 className="font-display text-2xl font-bold">Privacy Policy</h1>
      <p className="mt-1 text-sm text-surface-muted">
        Draft — pending legal review. Last updated 9 August 2026.
      </p>

      <div className="mt-6 flex flex-col gap-6">
        {SECTIONS.map((s) => (
          <section key={s.heading}>
            <h2 className="text-base font-semibold">{s.heading}</h2>
            {s.body.map((p) => (
              <p key={p} className="mt-2 text-sm leading-relaxed text-surface-subtle">
                {p}
              </p>
            ))}
          </section>
        ))}
      </div>
    </>
  );
}
